# Outdated... initial draft but the correct one is (for dev) is on the services project
db:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"
web:
  image: interactivelabs/process-admin
  command: npm start
  volumes:
    - "./node_app:/myapp"
  ports:
    - "9000:9000"
  links:
    - "db:mongo"
services:
  image: interactivelabs/services
  command: mvn compile exec:java
  ports:
    - "8080:8080"
